### ISSUE TITLE
Use of asgs:category for MeshBlock category is unclear

### ISSUE THREAD

**Issue by ashleysommer** [AGLDWG/asgs-ont#1]
I'm not sure whether asgs:category maps a MeshBlock to its MB:MB_CATEGORY_CODE_2016 or its MB:MB_CATEGORY_NAME_2016.
The range of the property being xsd:string indicates it should be the Category Name, but all other "Code2016" style properties in the ontology are also of range xsd:string, so MB_CATEGORY_CODE_2016 could fit here too.

The problem with mapping asgs:category to MB:MB_CATEGORY_CODE_2016 is the code is meaningless without turning the category code into a URI and linking it to a controlled and published vocabulary to look up the code.

So I am just mapping it to MB:MB_CATEGORY_NAME_2016 for now. 

Let me know what you think.

**Comment by dr-shorthair** [comment]
I think it is supposed to take a value from the list here: https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Mesh%20Blocks%20(MB)~10012
i.e. 
- residential
- commercial
- industrial
- parkland
- education
- hospital/medical
- transport
- primary production
- water
- other
See #13

**Comment by dr-shorthair** [comment]
`asgs:category` replaced by `dcterms:type` - https://github.com/AGLDWG/asgs-ont/pull/22 https://github.com/AGLDWG/asgs-ont/pull/20

Meshblock categories here https://github.com/AGLDWG/asgs-ont/blob/master/asgs-cat.ttl 

Data conversion script https://github.com/CSIRO-enviro-informatics/asgs-dataset/issues/13#issuecomment-567327344
