### ISSUE TITLE
seeAlso links are self-referential

### ISSUE THREAD

**Issue by dr-shorthair** [AGLDWG/asgs-ont#10]
The `rdfs:seeAlso` are kinda pointless as they loop back to the context URI. 
Could interact unpleasantly with reasoners. 
Any idea why they are there @laurentlefort @arminhaller ?

Found while addressing #8

**Comment by dr-shorthair** [comment]
Actually they are only self-referential on the classes. 
But on the object properties the refs are essentially compensating for the missing `rdfs:range` constraints - see #7

**Comment by arminhaller** [comment]
Agree, the way the are used atm is not useful, as far as I can tell and can cause some issues in implementations to introduce unnecessary loops.
