### ISSUE TITLE
Deploy updated asgs-ont.ttl

### ISSUE THREAD

**Issue by jyucsiro** [AGLDWG/asgs-ont#6]
An update to the asgs-ont.ttl was made to fix a typo - see https://github.com/AGLDWG/asgs-ont/commit/c97a31645ec4599d390ac9784d34c254d019101c

However, it still needs to be deployed so that this wget gets the updated version:
```
wget --header="Accept: text/turtle" http://linked.data.gov.au/def/asgs -O asgs.ont.ttl
```

How do we deploy this change?

**Comment by dr-shorthair** [comment]
I have done the following:

1. re-serialized asgs-ont.ttl using the OWL-API (via Protege) so the original author (Laurent Lefort) will be comfortable
2. tweaked the ontology metadata (added Nick and myself as contributors; added ORCIDs) and the ontology decription (copied the description from this repository's index.md)
3. regenerated the documentation using pyLODE, and re-inserted all the figures

http://catalogue.linked.data.gov.au/index.php/resource/28 is now updated to link to the new version, but http://linked.data.gov.au/def/asgs has not yet been rewired to point at the correct artefacts. @nicholascar is away for a week, so I've contacted @arminhaller to see if he can help. 
(with @laurentlefort in cc)

**Comment by dr-shorthair** [comment]
(with @laurentlefort in cc)

**Comment by dr-shorthair** [comment]
No-one can re-knit the redirects while @nicholascar is unavailable. I've proposed that the official URIs should redirect to GitHub so we the workflow for deploying revisions does not depend on Nick. See https://github.com/AGLDWG/ld-registers/issues/1

**Comment by dr-shorthair** [comment]
Revised [ASGS Ontology](http://linked.data.gov.au/def/asgs) went live 2020-02-03

SPARQL queries to convert data to the revised ontology are documented in https://github.com/CSIRO-enviro-informatics/asgs-dataset/issues/13 

Tag @laurentlefort FYI
